# Generated by Django 3.0.4 on 2021-05-16 03:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Factura')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tecnic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre Tecnico')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tecnico',
                'verbose_name_plural': 'Tecnicos',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='pay',
            options={'ordering': ['id'], 'verbose_name': 'Cobranza', 'verbose_name_plural': 'Cobranzas'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='cant',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='client',
            name='odorizador',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='client',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='abono',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción del Abono'),
        ),
        migrations.AddField(
            model_name='abono',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='abono/%Y/%m/%d/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='client',
            name='address_invoice',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Domicilio Factura'),
        ),
        migrations.AddField(
            model_name='client',
            name='data_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='data_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='client',
            name='position',
            field=models.IntegerField(blank=True, default=99, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='schedule',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Horario'),
        ),
        migrations.AddField(
            model_name='client',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pay',
            name='cli',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Client', verbose_name='Nombre del Cliente'),
        ),
        migrations.AddField(
            model_name='pay',
            name='date_pay',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='abono',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre del Abono'),
        ),
        migrations.AlterField(
            model_name='abono',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Precio del Abono'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='client',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre o Razon Social'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Sale', verbose_name='Id de Venta'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Total cobrado'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la zona')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('enable', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('tecnic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Tecnic', verbose_name='Nombre del Tecnico')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_odo', models.IntegerField(default=0, verbose_name='Cantidad Odorizadores')),
                ('cant_aer', models.IntegerField(default=0, verbose_name='Cantidad Aerosoles')),
                ('cant_got', models.IntegerField(default=0, verbose_name='Cantidad Goteos')),
                ('aerosoles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_aerosoles_abono', to='erp.Abono', verbose_name='Abono Aerosoles')),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Client', verbose_name='Nombre de cliente')),
                ('goteos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_goteos_abono', to='erp.Abono', verbose_name='Abono Goteos')),
                ('odorizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_odorizador_abono', to='erp.Abono', verbose_name='Abono Odorizador')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d', verbose_name='Imagen')),
                ('pvp', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de venta')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaySale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Total')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Client', verbose_name='Cliente')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Pay', verbose_name='Cobranza Id')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Sale', verbose_name='Id de Venta')),
            ],
            options={
                'verbose_name': 'Cobro de Venta',
                'verbose_name_plural': 'Cobros de ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PayInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Total')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Client', verbose_name='Cliente')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Invoice', verbose_name='Factura cobrada')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Pay', verbose_name='Cobranza Id')),
            ],
            options={
                'verbose_name': 'Cobro de factura',
                'verbose_name_plural': 'Cobros de factura',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='cli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Client', verbose_name='Cliente'),
        ),
        migrations.CreateModel(
            name='DetSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Sale')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_odo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant_odo', models.IntegerField(default=0)),
                ('price_aer', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant_aer', models.IntegerField(default=0)),
                ('price_got', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant_got', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Invoice')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalle de Facturas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='zone',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Zone', verbose_name='Nombre de Zona'),
        ),
        migrations.AddField(
            model_name='pay',
            name='tecnic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.Tecnic', verbose_name='Cobrador'),
        ),
    ]
