# Generated by Django 3.0.4 on 2021-05-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20210516_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='zone',
            field=models.CharField(default=0, max_length=150, verbose_name='Zona realizada'),
            preserve_default=False,
        ),
    ]
