# Generated by Django 3.0.4 on 2021-05-16 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_pay_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='cli',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='sale',
        ),
    ]
