# Generated by Django 3.0.4 on 2021-05-16 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20210516_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payinvoice',
            old_name='client',
            new_name='cli',
        ),
    ]
