# Generated by Django 3.0.4 on 2021-05-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20210516_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='type',
            field=models.CharField(default='no asignado', max_length=20, verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='type',
            field=models.CharField(default=0, max_length=20, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
