# Generated by Django 3.0.4 on 2021-05-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_auto_20210516_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paysale',
            old_name='client',
            new_name='cli',
        ),
    ]
