# Generated by Django 3.0.4 on 2021-06-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_auto_20210522_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type_pay',
            field=models.CharField(blank=True, choices=[('Ef', 'Efectivo'), ('Tr', 'Transferencia'), ('Ch', 'Cheque')], default='Ef', max_length=2, null=True, verbose_name='Tipo_pago'),
        ),
    ]
