# Generated by Django 3.2 on 2021-08-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_auto_20210819_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cuit',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Cuit'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Telefono'),
        ),
    ]
