# Generated by Django 3.2 on 2021-09-28 01:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_auto_20210825_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='dateWork',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de realizacion'),
        ),
        migrations.CreateModel(
            name='JobTecnic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha del trabajo')),
                ('cantEquipos', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de equipos realizados')),
                ('cantClient', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de clientes realizados')),
                ('tecnic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.tecnic', verbose_name='Tecnico')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.zone', verbose_name='Zona')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de pendiente')),
                ('dateRealized', models.DateField(blank=True, null=True, verbose_name='Fecha de pendiente')),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.client', verbose_name='Cliente pendiente id')),
                ('tecnic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.tecnic', verbose_name='Cliente pendiente tecnic')),
            ],
            options={
                'verbose_name': 'Cliente Pendiente',
                'verbose_name_plural': 'Clientes Pendientes',
                'ordering': ['id'],
            },
        ),
    ]
