# Generated by Django 3.2 on 2021-10-23 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_auto_20210927_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobtecnic',
            options={'ordering': ['id'], 'verbose_name': 'Cliente Pendiente', 'verbose_name_plural': 'Clientes Pendientes'},
        ),
        migrations.AddField(
            model_name='clientpending',
            name='dateToMake',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha a realizar'),
        ),
        migrations.AlterField(
            model_name='clientpending',
            name='dateRealized',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha realizado'),
        ),
        migrations.AlterField(
            model_name='jobtecnic',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.zone', verbose_name='Zona'),
        ),
    ]
