# Generated by Django 3.2 on 2021-10-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_auto_20211023_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpending',
            name='tecnic',
        ),
        migrations.AddField(
            model_name='clientpending',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo'),
        ),
    ]
