# Generated by Django 3.2 on 2021-11-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_auto_20211023_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='zone',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Zona realizada'),
        ),
    ]
