# Generated by Django 3.2.7 on 2022-01-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_alter_pay_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de Contacto'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default=0, max_length=150, verbose_name='Nombre o Razon Social'),
            preserve_default=False,
        ),
    ]
