# Generated by Django 3.2.7 on 2022-02-08 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_auto_20220119_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='zone',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.zone', verbose_name='Nombre de Zona'),
        ),
    ]
