# Generated by Django 3.2.7 on 2022-02-08 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_alter_client_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtecnic',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.zone', verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.zone', verbose_name='Zona realizada'),
        ),
    ]
