# Generated by Django 3.2.7 on 2022-04-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_auto_20220208_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='suspend',
            field=models.BooleanField(default=False, verbose_name='Suspender'),
        ),
    ]
