# Generated by Django 3.2.7 on 2022-04-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_client_suspend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='suspend',
        ),
        migrations.AddField(
            model_name='client',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activado'),
        ),
    ]
