# Generated by Django 3.2.7 on 2022-04-02 20:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_auto_20220402_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipSuspend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Suspensión')),
                ('date_end', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Reactivación')),
                ('cantOdo', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de odorizadores retirados')),
                ('cantAer', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de aerosoles retirados')),
                ('cantGot', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de goteos retirados')),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cliente Retirado',
                'verbose_name_plural': 'Clientes Retirados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EquipRemove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Retiro')),
                ('cantOdo', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de odorizadores retirados')),
                ('cantAer', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de aerosoles retirados')),
                ('cantGot', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de goteos retirados')),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cliente Retirado',
                'verbose_name_plural': 'Clientes Retirados',
                'ordering': ['id'],
            },
        ),
    ]
