# Generated by Django 3.2.7 on 2022-04-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0025_alter_equipsuspend_date_end'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipsuspend',
            options={'ordering': ['id'], 'verbose_name': 'Cliente Suspendido', 'verbose_name_plural': 'Clientes Suspendidos'},
        ),
        migrations.AlterField(
            model_name='equipsuspend',
            name='cantAer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de aerosoles suspendidos'),
        ),
        migrations.AlterField(
            model_name='equipsuspend',
            name='cantGot',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de goteos suspendidos'),
        ),
        migrations.AlterField(
            model_name='equipsuspend',
            name='cantOdo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de odorizadores suspendidos'),
        ),
        migrations.AlterField(
            model_name='equipsuspend',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Reactivación'),
        ),
    ]
