# Generated by Django 3.2.7 on 2022-05-08 00:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_auto_20220406_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abono',
            name='image',
        ),
        migrations.AddField(
            model_name='abono',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha Creación de Abono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abono',
            name='date_updated',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Actualización de Abono'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abono',
            name='type',
            field=models.CharField(blank=True, choices=[('Od', 'Odorizador'), ('Ae', 'Aerosol'), ('Go', 'Goteo')], default='Od', max_length=2, null=True, verbose_name='Tipo_abono'),
        ),
    ]
