# Generated by Django 3.2.7 on 2022-06-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0027_auto_20220507_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtecnic',
            name='totalFact',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Facturado $'),
        ),
        migrations.AlterField(
            model_name='abono',
            name='type',
            field=models.CharField(blank=True, choices=[('Od', 'Odorizador'), ('Ae', 'Aerosol'), ('Go', 'Goteo')], default='Od', max_length=2, null=True, verbose_name='Tipo Abono'),
        ),
    ]
