# Generated by Django 3.2.7 on 2022-07-04 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_auto_20220607_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='aerosoles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_aerosoles_abono', to='erp.abono', verbose_name='Abono Aerosoles'),
        ),
        migrations.AlterField(
            model_name='services',
            name='goteos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_goteos_abono', to='erp.abono', verbose_name='Abono Goteos'),
        ),
        migrations.AlterField(
            model_name='services',
            name='odorizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_odorizador_abono', to='erp.abono', verbose_name='Abono Odorizador'),
        ),
    ]
